### ISSUE TITLE
Can't use the init-generator on my existing project

### ISSUE THREAD

**Issue by Suven** [poetic/ember-cli-cordova#156]
Hey,

while I am able to use ember-cli-cordova on new projects, it does not seem to work on my existing project. I have trouble hunting down what might be the issue. I checked that the /cordova-dir does not exists and checked if the versions of most packages (ember, ember-cli, ember-cli-cordova, cordova, fs-extra..) are the same as in fresh projects. I also tried running the generator with sudo (just for the sake of testing it) and checked the dirs file permissions.

This is what is returned

```
 $= ember generate cordova-init de.neomatt.itemfinder
version: 0.2.7
installing
[?] Overwrite config/environment.js? No, skip
[?] Overwrite .gitignore? No, skip
  skip config/environment.js
  skip .gitignore
Creating Cordova project
Creating a new cordova project with name "Itemfinder" and id "de.neomatt.itemfinder" at location "/Users/sven/fooproject/cordova"
Creating Cordova project...
Adding ios platform to cordova..
Adding ios project...
iOS project created with cordova-ios@3.8
Update config.xml with your project settings...
Building ember app since dist/ dir doesn't exist yet..
version: 0.2.7
BuildingBuilding.Building..Building...BuildingBuilding.Building..Build failed.
EEXIST, file already exists '/Users/sven/fooproject/cordova/www'
Error: EEXIST, file already exists '/Users/sven/fooproject/cordova/www'
    at Error (native)
    at Object.fs.mkdirSync (evalmachine.<anonymous>:747:18)
    at Object.mkdirsSync (/Users/sven/fooproject/node_modules/ember-cli/node_modules/fs-extra/lib/mkdir.js:71:9)
    at /Users/sven/fooproject/node_modules/ember-cli/lib/models/builder.js:85:12
    at lib$rsvp$$internal$$initializePromise (/Users/sven/fooproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:537:9)
    at PromiseExt.lib$rsvp$promise$$Promise [as _superConstructor] (/Users/sven/fooproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:850:9)
    at new PromiseExt (/Users/sven/fooproject/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.copyToOutputPath (/Users/sven/fooproject/node_modules/ember-cli/lib/models/builder.js:83:12)
    at /Users/sven/fooproject/node_modules/ember-cli/lib/models/builder.js:97:21
    at lib$rsvp$$internal$$tryCatch (/Users/sven/fooproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)

Error thrown while running shell command: "ember build"
Error: Command failed: /bin/sh -c ember build

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)%
```

**Comment by Suven** [comment]
This was caused by a custom outputPath in `.ember-cli`
