### ISSUE TITLE
Error running ember generate cordoba-init com.test.app --platform=android

### ISSUE THREAD

**Issue by marksalpeter** [poetic/ember-cli-cordova#178]
here's the full output 
```console
version: 1.13.13
The option '--platform' is not registered with the generate command. Run `ember generate --help` for a list of supported options.
ember-cli-cordova: You must specify the locationType as 'hash' in your environment.js or rename it to defaultLocationType.
Error: ember-cli-cordova: You must specify the locationType as 'hash' in your environment.js or rename it to defaultLocationType.
    at Class.module.exports.config (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli-cordova/index.js:24:15)
    at /Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/models/project.js:224:27
    at Array.reduce (native)
    at Project.getAddonsConfig (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/models/project.js:222:22)
    at Project.config (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/models/project.js:200:29)
    at Class.Blueprint.install (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/models/blueprint.js:483:32)
    at Class.module.exports.Task.extend.run (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:60:49)
    at Class.module.exports.Command.extend.run (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/commands/generate.js:77:17)
    at Class.<anonymous> (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/lib/models/command.js:151:17)
    at lib$rsvp$$internal$$tryCatch (/Users/Mark/Dealyze/projects/tablet-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
```

**Comment by marksalpeter** [comment]
changing `ENV.locationType = "auto"`  to `ENV.defaultLocationType = "auto"` in config/environment.js fixed the problem.

**Comment by dukex** [comment]
@marksalpeter you are right, like said the Getting Started, you need change the `locationType`:
 
> You just need to move your locationType setting in config/environment.js to defaultLocationType so that it'd be used when not building for cordova (cordova needs hash as locationType).

https://github.com/poetic/ember-cli-cordova/blob/master/docs/getting-started.md#developing-the-app
